//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXe.Areas.Admin.Models.DaXeDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_Car> Table_Car { get; set; }
        public virtual DbSet<Table_CarOwner> Table_CarOwner { get; set; }
        public virtual DbSet<Table_DetailedRoadmap> Table_DetailedRoadmap { get; set; }
        public virtual DbSet<Table_Driver> Table_Driver { get; set; }
        public virtual DbSet<Table_Order> Table_Order { get; set; }
        public virtual DbSet<Table_Route> Table_Route { get; set; }
        public virtual DbSet<Table_User> Table_User { get; set; }
    }
}
