//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXe.Areas.Admin.Models.DaXeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Route()
        {
            this.Table_DetailedRoadmap = new HashSet<Table_DetailedRoadmap>();
        }
    
        public int ID { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public string Address { get; set; }
        public Nullable<int> IDCar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_DetailedRoadmap> Table_DetailedRoadmap { get; set; }
        public virtual Table_Car Table_Car { get; set; }
    }
}
