//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXe.Areas.Admin.Models.DaXeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Order
    {
        public int IDCar { get; set; }
        public int IDUser { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> Number { get; set; }
    
        public virtual Table_Car Table_Car { get; set; }
        public virtual Table_User Table_User { get; set; }
    }
}
