//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaXe.Areas.Admin.Models.DaXeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_CarOwner
    {
        public int ID { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Name { get; set; }
        public string Facebook { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> IDCar { get; set; }
    
        public virtual Table_Car Table_Car { get; set; }
    }
}
